### ISSUE TITLE
缩放了图片，导致截图不清晰

### ISSUE THREAD

**Issue by nashaofu** [WumaCoder/fltk-demo#1]
https://github.com/WumaCoder/fltk-demo/blob/c4ae6a9ca6aed0532ea3e6d6a565d1e12b2b41c2/src/main.rs#L82

**Comment by Lydanne** [comment]
我试试

**Comment by Lydanne** [comment]
> https://github.com/WumaCoder/fltk-demo/blob/c4ae6a9ca6aed0532ea3e6d6a565d1e12b2b41c2/src/main.rs#L82

但是不锁放显示的又太大😭，不过问题找到了，感谢
